name = "5ch-tracker"
compatibility_date = "2024-04-03"
main = "src/index.ts"

[triggers]
#crons = ["*/10 13-21 * * 1-5"]
crons = ["*/2 * * * *"]
[[d1_databases]]
binding = "DB"
database_name = "stock-rankings"
database_id = "621699fa-e616-44f1-a52b-2904a4ff069f"

[observability]
enabled = true
